version: "3.8"

services:
    db:
        image: mongo
        restart: unless-stopped
        volumes:
        - dbdata:/data/db
        expose: 
        - 27017
    
    redis :
        restart: unless-stopped
        image : redis:alpine
        expose :
        - 6379

    web:
        build: .
        image: node:12.13.0-alpine
        restart: unless-stopped
        env_file: .env
        ports:
            - 3000:3000
        volumes:
            - .:/code
        command: sh -c "/entrypoint" 
        
volumes:
    dbdata:
